# Generated by Django 4.2.7 on 2025-08-23 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(help_text='Name of the interface/module', max_length=255)),
                ('function', models.CharField(help_text='Function or purpose of the interface', max_length=255)),
                ('url', models.CharField(help_text='URL pattern for the interface', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Interface',
                'verbose_name_plural': 'Interfaces',
                'db_table': 'interfaces',
            },
        ),
        migrations.CreateModel(
            name='UserInterfaceAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_access', models.BooleanField(default=False)),
                ('granted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User Interface Access',
                'verbose_name_plural': 'User Interface Access',
                'db_table': 'userinterfaceaccess',
            },
        ),
    ]
