# Generated by Django 4.2.7 on 2025-08-25 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_description_exam_end_time_exam_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
